runtime: nodejs
env: flex
service: eureka-api
env_variables:
  APPINSIGHTS_INSTRUMENTATIONKEY: 20f0c386-44e4-4eea-97be-2644299652e5
  EUREKA_ENV: dev
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: dotted-vim-164110:us-east1:eureka-dev
