runtime: nodejs
env: flex
service: default
env_variables:
  APPINSIGHTS_INSTRUMENTATIONKEY: 2258b7bb-b7f9-4497-899c-3b3493a64ac8
  EUREKA_ENV: dev
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: dotted-vim-164110:us-east1:eureka-dev

# Instance resources size
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
# Disable auto-scale
manual_scaling:
  instances: 1

# Disable health checks
health_check:
  enable_health_check: False
